version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.16.0-jessie
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Compile
          command: npm run truffle-compile
      - run:
          name: Migrate
          command: npm run ganache > /dev/null & sleep 10 && npm run truffle-migrate
      - run:
          name: Test
          command: npm run truffle-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
